Repository nhost/hasura-auth, pull requests merged in 2022-01, with the labels that each got.

#61 Correct typos
  src/routes/signin/passwordless/email.ts
  src/utils/user/deanonymize-passwordless-email.ts
Labels: typo

#59 fix: better error message for redirectTo
  src/routes/signin/passwordless/email.ts
  src/routes/signup/email-password.ts
  src/routes/user/email/change.ts
  src/routes/user/email/send-verification-email.ts
  src/routes/user/password-reset.ts
  src/utils/email.ts
  src/utils/user/deanonymize-email-password.ts
  src/utils/user/deanonymize-passwordless-email.ts
  test/routes/signin/passwordless/email.test.ts
Labels: enhancement

#63 feat(emails): translate email templates to french
  email-templates/fr/email-confirm-change/body.html
  email-templates/fr/email-confirm-change/subject.txt
  email-templates/fr/email-verify/body.html
  email-templates/fr/email-verify/subject.txt
  email-templates/fr/password-reset/body.html
  email-templates/fr/password-reset/subject.txt
  email-templates/fr/signin-passwordless/body.html
  email-templates/fr/signin-passwordless/subject.txt
Labels: enhancement, help wanted
